### ISSUE TITLE
Migrate currency amounts to proper decimal fields

### ISSUE THREAD

**Issue by kasimos** [SFTtech/abrechnung#110]
Float or Doubles are not a good choice for representing currency amounts.
A migration to a stable decimal number datatype should be accurate and is highly recommended.

According to ISO 4217 there is currently a maximum of 4 decimals in any of the currently active currencies, so a type like Number(10,4) would be sufficient for values up to 999999.9999 which should be more than enough and a migration to a higher precision isn't a big deal later on.

**Comment by mikonse** [comment]
Fixed point numbers, i.e. fixed decimal numbers would work quite well in a case where only addition, subtraction or multiplication is used to calculate account balances.

Unfortunately, we also have to use division to properly calculate the fractional transaction shares when splitting a bill.
E.g. a bill of 10€ split three ways will lead to a balance change of 10 / 3 € = 3.33....€ for each transaction participant. The most accurate way of calculating the resulting balance is to use doubles as any fixed point decimal (with a smaller precision than doubles) will lead to a larger approximation error. Your proposition of using a Number(10,4) would lead to a quite noticeable approximation error. A good way of dealing with this problem is to simply use doubles all the way and only round to 2 decimal places before displaying currency values. 

While using fixed point decimals with a higher precision is possible as e.g. PostgreSQL natively supports such a datatype it would not result in a noticeable improvement in approximation accuracy for account balances as we always round to 2 decimal places anyways.
