### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by marcogiorgio** [SFTtech/abrechnung#177]
Hi!
Just wanted to ask if there is an Android app somewhere because I came across a reddit [post](https://www.reddit.com/r/selfhosted/comments/wij989/selfhosted_money_splitting_expense_splitting/) in which you said it was in development, but I couldn't find it.
Thanks

**Comment by mikonse** [comment]
Hi, there is an android app (`frontend/apps/mobile`) built with react native.
Currently I'm actively developing it since it's not yet fully feature complete and has got some bugs.
Also it's not yet automatically built in the CI pipeline and the APK is not available in the github releases / play store / fdroid.
My plan is to have it automatically be built in the CI and downloadable (hopefully) this month at the next github release.

If you want to build it locally it's unfortunately not very straight forward atm so the best way is to wait until the next release. It'll be downloadable then.

I'll keep this issue open until then.

**Comment by mikonse** [comment]
Great news! The app can now be installed from the github releases.
