### ISSUE TITLE
Docker multi-arch support

### ISSUE THREAD

**Issue by RicardoJeronimo** [SFTtech/abrechnung#187]
I'm trying to setup this project on a Raspberry Pi 3 and I'm getting the following error when creating both api and frontend containers:

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

Please consider adding multi-arch support during builds, e.g. as described [here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).

Thank you!

**Comment by mikonse** [comment]
I've added an `linux/arm64/v8` platform to the docker image. Can you check whether that one works for raspberry pi 3?

Adding `arm/v7` support as well would require some more tweaking with the docker image as it requires a rust compiler due to missing prebuilt python wheels.

**Comment by RicardoJeronimo** [comment]
Thanks for the quick response!

I tried to pull the "latest" tag and get the following error on a Raspberry Pi 3:

`no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by mikonse** [comment]
Ah ok, it seems that raspberry pi 3 requires arm/v7 instead of arm64/v8. I'll have a look at how easy it's going to be to build that as well.

**Comment by mikonse** [comment]
Ok, so after playing around a bit it seems like building for arm/v7 is not really feasible for this projects dependency chain.

Raspberry pi 3 should support arm64/v8 though, you probably have to check which architecture your raspbian (or other distro) was built for and change to the arm64/v8 version for that.

I'll close this for now since arm/v8 is supported now and should also run on raspberry pi 3

**Comment by RicardoJeronimo** [comment]
My OS is indeed 32bit, I will eventually migrate to Debian 64bit and test the image again.

I can confirm it works on a Raspberry Pi 4 running Debian 64bit.
