### ISSUE TITLE
helper to settle balances

### ISSUE THREAD

**Issue by mikonse** [SFTtech/abrechnung#19]
Implement a small helper in the UI to show the most efficient way to settle the balances in a group, e.g. for balances

* A: -20€
* B: 10€
* C: 10€

this would result in the instructions
* A->B: 10€
* A->C: 10€

**Comment by natrius** [comment]
Just to be sure: Set the balance to 0 afterwards. So in a shared flat it can be done every month or so.

**Comment by mikonse** [comment]
I think there's a two step process to this feature right?

First of all we want to get the optimal way for people to pay each other s.t. the balance is 0 afterwards.
Then people obviously have to pay first. 
In a second step we could then use a convenience function to click on one of the proposed transfers to mark it as payed which would then create a new transfer in the group. Once everybody has payed and we have clicked on "payed" for each proposal the balance will be 0.

Does that flow match what you are expecting from that feature or do you have something else in mind?

**Comment by natrius** [comment]
Tbh, from my experience, simply set the balance to 0 and the "Mark payed" stuff is an extra info stored at the account or something like that. 
Because Person A might pay the day you "settle" but Person B might forget and pay 2 weeks later. In these 2 weeks new stuff gets bought again and the balance changes again. I think it would be better if "Settle" is pressed to really set the balance to 0 and add a simpley checkbox somewhere (or something like that).

**Comment by mikonse** [comment]
Hmm, the thing is that model does not quite fit our current way of modeling account balances.

Currently the balances are always computed based on the transactions an account is involved in (which might change over time).

So in order to settle a balance one would always need to create a transfer which represents that payment.

Otherwise we'd have an issue.
What if we have a long-lived group where balances were settled multiple times and new transactions were added afterwards again? Marking an account as settled without having a dedicated transfer for that cash flow would not work in that case.

Towards the problem of people paying later and the balance changing again. I don't see how even a settled button is going to solve that issue. In case somebody pays way later you'd either have a settled balance in the group without the person actually having payed for some time or you'd always need to manually enter the amount the person payed afterwards.

**Comment by natrius** [comment]
Seems like i misunderstood something. I used the app "Tricky Tripper" for travels some time ago, it was a neat app, quick to enter stuff and so on, but not developed anymore. Here you got at the end and settle and go on with your life, so there is nothing later. 
Flatastic is the one for the shared flat. Everyone enters what they buy for the whole flat (and even mark to exclude someone) and the whole sum adds up. When pressing "Settle" everybody gets an e-mail "X has to pay Y the amount of AA" and the whole balance is simply set back to 0. And from then on everybody can buy stuff again. It does not matter for that balance if someone has paid alreay because its not a money management system like GnuCash or FireflyIII or anything. Its just so the stuff in the shared flat gets sorted out. 

But i will look into the demo again and see what i missed :)

**Comment by TheJJ** [comment]
we have a settle assistant by now.
