### ISSUE TITLE
Incorrect math in Settlement Plan

### ISSUE THREAD

**Issue by RicardoJeronimo** [SFTtech/abrechnung#194]
Consider the following transactions created in the Demo:

![image](https://github.com/SFTtech/abrechnung/assets/4950815/ec27ba47-e4f9-45bc-bc1e-63ca7312e75d)

Balance table shows correct division:

![image](https://github.com/SFTtech/abrechnung/assets/4950815/5c8518dd-887a-4bbb-b76e-a548aaafae93)

However, on the Settle Up page, some users don't have debts they should (i.e. Bob should be paying Cat), and some users have debts they shouldn't have (i.e. Joe doesn't own Bob any money)

![image](https://github.com/SFTtech/abrechnung/assets/4950815/dca0d8ed-3705-48b3-ba0b-cb2c9bba6360)

**Comment by mikonse** [comment]
I think there might be a small misunderstanding as to how the balance computation and proposed settlements work.

Contrary to how e.g. tricount does this Abrechnung does not track per-person debts but rather computes an aggregated balance per person over all transactions in a group. Therefore we just show a simply balance in the balance overview rather than a list of x ows y z amount.

The settelement plan computes proposed transactions to get all balances to 0 with the least amount of transactions between users.

**Comment by RicardoJeronimo** [comment]
After spending some time with a calculator I now understand what you mean.

I apologize for the misunderstanding, I think this is a great functionality!
